return {
    {
        Name = "Workspace",
        ClassName = "Workspace",
        Children = {
            {
                Name = "Baseplate",
                ClassName = "Part",
            },
            {
                Name = "Model",
                ClassName = "Model",
                Children = {
                    {
                        Name = "Part",
                        ClassName = "Part",
                    }
                }
            }
        }
    }
}
